local override + container fix

diff --git a/site/scripts/container-npx b/site/scripts/container-npx
--- a/site/scripts/container-npx
+++ b/site/scripts/container-npx
@@ -1,3 +1,4 @@
+#!/usr/bin/env sh
 #
 # Copyright 2026 The Apache Software Foundation
 #
@@ -5,7 +6,7 @@
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
-# http://www.apache.org/licenses/LICENSE-2.0
+#     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
@@ -13,17 +14,29 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-__pycache__/
-/pipeline/.idea/
-/pipeline/.venv/
-/.stage/
-/.preview/
-/.public/
-/.hugo_build.lock
-/.container-home/
-/resources/
-/node_modules/
-/build/
+set -eu
 
-# Local overrides
-/components.local.yaml
+real_npx="$(command -v npx || true)"
+
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+    --no-install|-y|--yes)
+      shift
+      continue
+      ;;
+    postcss)
+      shift
+      exec postcss "$@"
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
+
+if [ -n "$real_npx" ]; then
+  exec "$real_npx" "$@"
+fi
+
+printf 'Error: npx fallback is unavailable and postcss was not requested.\n' >&2
+exit 127
